Repository UQcsse3200/2025-studio-1, pull requests merged in 2025-09, with the labels that each got.

#73 Player stamina
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/test/com/csse3200/game/components/player/PlayerStaminaTest.java
Labels: sprint 1, team-4, task

#70 Weapons
  source/build.gradle
  source/core/assets/images/rifle.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/entity/item/ItemComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/DaggerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/RifleConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponsFactory.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: sprint 1, team-7

#79 Fixed a major bug where the game freeze when gpt enemy dies
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: bug, sprint 1, team-2, team-7

#92 DisableDamage CheatCode
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DisableDamageCommand.java
Labels: team-5

#118 Fixed game freeze that occurred when enemies died after clicking the Kill Enemy button
  source/core/assets/images/Deepspin.atlas
  source/core/assets/images/Deepspin.png
  source/core/assets/images/Grokdroid.atlas
  source/core/assets/images/Grokdroid.png
  source/core/assets/images/Vroomba.atlas
  source/core/assets/images/Vroomba.png
  source/core/assets/images/ghostGPT.atlas
  source/core/assets/images/ghostGPT.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/BossFactory.java
Labels: bug, sprint 2, team-2

#152 Upgrade Stations Style Fix
  source/core/src/main/com/csse3200/game/components/WeaponsStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
Labels: sprint 2, team-7

#151 Item Spawning System and Respawning dropped items
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/ItemPickUpComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/entities/configs/ItemSpawnConfig.java
  source/core/src/main/com/csse3200/game/entities/spawner/ItemSpawner.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickUpComponentTest.java
  source/core/src/test/com/csse3200/game/entities/spawner/ItemSpawnerTest.java
Labels: sprint 2, team-1, task

#157 Tutorial
  AI-use-team5.md
  source/core/assets/images/arrow-left.png
  source/core/assets/images/arrow-right.png
  source/core/assets/images/background.png
  source/core/assets/images/tutorial/move/frame_0001.png
  source/core/assets/images/tutorial/move/frame_0002.png
  source/core/assets/images/tutorial/move/frame_0003.png
  source/core/assets/images/tutorial/move/frame_0004.png
  source/core/assets/images/tutorial/move/frame_0005.png
  source/core/assets/images/tutorial/move/frame_0006.png
  source/core/assets/images/tutorial/move/frame_0007.png
  source/core/assets/images/tutorial/move/frame_0008.png
  source/core/assets/images/tutorial/move/frame_0009.png
  source/core/assets/images/tutorial/move/frame_0010.png
  source/core/assets/images/tutorial/move/frame_0011.png
  source/core/assets/images/tutorial/move/frame_0012.png
  source/core/assets/images/tutorial/move/frame_0013.png
  source/core/assets/images/tutorial/move/frame_0014.png
  source/core/assets/images/tutorial/move/frame_0015.png
  source/core/assets/images/tutorial/move/frame_0016.png
  source/core/assets/images/tutorial/move/frame_0017.png
  source/core/assets/images/tutorial/move/frame_0018.png
  source/core/assets/images/tutorial/move/frame_0019.png
  source/core/assets/images/tutorial/move/frame_0020.png
  source/core/assets/images/tutorial/move/frame_0021.png
  source/core/assets/images/tutorial/move/frame_0022.png
  source/core/assets/images/tutorial/move/frame_0023.png
  source/core/assets/images/tutorial/move/frame_0024.png
  source/core/assets/images/tutorial/move/frame_0025.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/BaseEndScreenDisplays.java
  source/core/src/main/com/csse3200/game/components/screens/BaseScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/DeathScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/TutorialClip.java
  source/core/src/main/com/csse3200/game/components/screens/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/TutorialStep.java
  source/core/src/main/com/csse3200/game/components/screens/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/screens/BaseScreen.java
  source/core/src/main/com/csse3200/game/screens/DeathScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/screens/WinScreen.java
  source/core/src/main/com/csse3200/game/ui/AnimatedClipImage.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/WinScreenCommand.java
  source/core/src/test/com/csse3200/game/components/screens/AnimatedClipImageTest.java
  source/core/src/test/com/csse3200/game/components/screens/TutorialClipTest.java
  source/core/src/test/com/csse3200/game/components/screens/TutorialScreenDisplayTest.java
  source/core/src/test/com/csse3200/game/components/screens/TutorialStepTest.java
Labels: sprint 2, team-5, feature

#176 Attachments
  source/core/assets/images/lightSaber.atlas
  source/core/assets/images/waterBullet.png
  source/core/assets/sounds/ammo_replenished.mp3
  source/core/assets/sounds/laser_blast.mp3
  source/core/assets/sounds/reload.mp3
  source/core/assets/sounds/shot_failed.mp3
  source/core/src/main/com/csse3200/game/areas/.ForestGameArea.java.un~
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/AmmoStatsComponent.java
  source/core/src/main/com/csse3200/game/components/MagazineComponent.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/TagComponent.java
  source/core/src/main/com/csse3200/game/components/WeaponsStatsComponent.java
  source/core/src/main/com/csse3200/game/components/attachments/BulletEnhancerComponent.java
  source/core/src/main/com/csse3200/game/components/attachments/LaserComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/EnemyDeathRewardComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/EnemyProjectileDamageComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/stations/StationComponent.java
  source/core/src/main/com/csse3200/game/effects/RapidFireEffect.java
  source/core/src/main/com/csse3200/game/entities/configs/consumables/RapidFireConsumableConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/.WeaponsFactory.java.un~
  source/core/src/main/com/csse3200/game/entities/factories/InteractableStationFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PowerupsFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/characters/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/items/WeaponsFactory.java
  source/core/src/main/com/csse3200/game/rendering/RenderComponent.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderWithRotationComponent.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/components/WeaponsStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/attachments/BulletEnhancerComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/EnemyDeathRewardComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MagazineComponentTest.java
  source/core/src/test/com/csse3200/game/entities/ProjectileFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/WeaponsFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/InteractableStationFactoryTest.java
Labels: sprint 2, team-7, task

#188 Enemy Spawning, Enemy Sound Effects and Tests
  source/core/assets/images/Vroomba.atlas
  source/core/assets/images/Vroomba.png
  source/core/assets/images/Vroomba.png~
  source/core/assets/images/test.atlas
  source/core/assets/sounds/enemyDamage.mp3
  source/core/assets/sounds/enemyDeath.mp3
  source/core/assets/sounds/jump.mp3
  source/core/src/main/com/csse3200/game/areas/ElevatorGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainHall.java
  source/core/src/main/com/csse3200/game/areas/OfficeGameArea.java
  source/core/src/main/com/csse3200/game/areas/Reception.java
  source/core/src/main/com/csse3200/game/areas/ResearchGameArea.java
  source/core/src/main/com/csse3200/game/areas/SecurityGameArea.java
  source/core/src/main/com/csse3200/game/areas/ServerGameArea.java
  source/core/src/main/com/csse3200/game/areas/ShippingGameArea.java
  source/core/src/main/com/csse3200/game/areas/StorageGameArea.java
  source/core/src/main/com/csse3200/game/areas/TunnelGameArea.java
  source/core/src/main/com/csse3200/game/components/SoundComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/DeathParticleSpawnerComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/EnemyHealthDisplay.java
  source/core/src/main/com/csse3200/game/components/enemy/EnemyWaves.java
  source/core/src/main/com/csse3200/game/components/enemy/ProjectileLauncherComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/GPTFastChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/GPTGroundFastChaseTask.java
  source/core/src/main/com/csse3200/game/entities/factories/characters/NPCFactory.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/test/com/csse3200/game/components/SoundComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/EnemyDeathRewardComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/EnemyHealthDisplayTest.java
  source/core/src/test/com/csse3200/game/components/enemy/EnemyWavesTest.java
  source/core/src/test/com/csse3200/game/components/enemy/LowHealthAttackBuffComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/VroombaSuicideComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/DashAttackTaskTest.java
  source/core/src/test/com/csse3200/game/physics/components/EnemyJumpTest.java
  source/core/src/test/com/csse3200/game/rendering/AnimationRenderComponentTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/WavesCommandTest.java
Labels: sprint 2, team-2, feature

#174 Upgrade stations
  source/core/assets/configs/player.json
  source/core/assets/images/healthBench.png
  source/core/assets/images/speedBench.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/stations/StationComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/Benches.java
  source/core/src/main/com/csse3200/game/entities/configs/ItemTypes.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/BenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/ComputerBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/HealthBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/SpeedBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/characters/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/InteractableStationFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/items/WeaponsFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/test/com/csse3200/game/components/stations/StationComponentTests.java
  source/core/src/test/com/csse3200/game/entities/configs/BenchesTest.java
  source/core/src/test/com/csse3200/game/entities/configs/benches/ComputerBenchConfigTest.java
  source/core/src/test/com/csse3200/game/entities/configs/benches/HealthBenchConfigTest.java
  source/core/src/test/com/csse3200/game/entities/configs/benches/SpeedBenchConfigTest.java
  source/core/src/test/com/csse3200/game/entities/configs/benches/WeaponsTest.java
  source/core/src/test/com/csse3200/game/entities/configs/weapons/WeaponConfigsTest.java
  source/core/src/test/com/csse3200/game/entities/factories/InteractableStationFactoryTest.java
Labels: sprint 2, team-7, task

#191 Fixed top and bottom border rendering bug
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/test/com/csse3200/game/areas/Floor2GameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/GameAreaBoundsTest.java
Labels: bug, sprint 2, team-5

#187 Added 5 more Rooms and Completed map layout
  assets/wiki/ShippingWiki.png
  assets/wiki/StorageWiki.png
  source/core/assets/foreg_sprites/Research/Laboratory.png
  source/core/assets/foreg_sprites/Research/Microscope.png
  source/core/assets/foreg_sprites/Research/ResearchDesk.png
  source/core/assets/foreg_sprites/Research/ResearchPod.png
  source/core/assets/images/Mhall-holo.png
  source/core/assets/images/Mhall-screen.png
  source/core/assets/images/Mhall-sofa.png
  source/core/assets/images/Office and elevator/Elevator background.png
  source/core/assets/images/Office and elevator/Office Background.png
  source/core/assets/images/Office and elevator/Office desk.png
  source/core/assets/images/Office and elevator/Office platform.png
  source/core/assets/images/Office and elevator/Office stuff.png
  source/core/assets/images/Office and elevator/Platform for elevator.png
  source/core/assets/images/Office and elevator/desk in office.png
  source/core/assets/images/Office and elevator/table chair ceo.png
  source/core/assets/images/ResearchBackground.png
  source/core/assets/images/Shipping.png
  source/core/assets/images/Storage.png
  source/core/assets/images/TunnelRoomBackgResize.png
  source/core/assets/images/platform-3.png
  source/core/src/main/com/csse3200/game/areas/ElevatorGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainHall.java
  source/core/src/main/com/csse3200/game/areas/OfficeGameArea.java
  source/core/src/main/com/csse3200/game/areas/Reception.java
  source/core/src/main/com/csse3200/game/areas/ResearchGameArea.java
  source/core/src/main/com/csse3200/game/areas/SecurityGameArea.java
  source/core/src/main/com/csse3200/game/areas/ServerGameArea.java
  source/core/src/main/com/csse3200/game/areas/ShippingGameArea.java
  source/core/src/main/com/csse3200/game/areas/StorageGameArea.java
  source/core/src/main/com/csse3200/game/areas/TunnelGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/entities/configs/ItemSpawnConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/system/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/spawner/ItemSpawner.java
  source/core/src/test/com/csse3200/game/areas/ElevatorAreaTest.java
  source/core/src/test/com/csse3200/game/areas/MainHallAreaTest.java
  source/core/src/test/com/csse3200/game/areas/OfficeAreaTest.java
  source/core/src/test/com/csse3200/game/areas/ReceptionAreaTest.java
  source/core/src/test/com/csse3200/game/areas/ResearchAreaTest.java
  source/core/src/test/com/csse3200/game/areas/SecurityAreaTest.java
  source/core/src/test/com/csse3200/game/areas/ServerAreaTest.java
  source/core/src/test/com/csse3200/game/areas/ShippingAreaTest.java
  source/core/src/test/com/csse3200/game/areas/StorageAreaTest.java
  source/core/src/test/com/csse3200/game/areas/TunnelAreaTest.java
Labels: sprint 2, team-3, feature

#194 Game crash prevention
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
Labels: team-7

#182 Cheat codes
  source/core/scripts/png_to_atlas_json.py
  source/core/src/main/com/csse3200/game/components/DoorComponent.java
  source/core/src/main/com/csse3200/game/components/KeycardGateComponent.java
  source/core/src/main/com/csse3200/game/components/WeaponsStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/ItemPickUpComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
  source/core/src/main/com/csse3200/game/ui/terminal/TerminalDisplay.java
  source/core/src/main/com/csse3200/game/ui/terminal/autocomplete/BKTree.java
  source/core/src/main/com/csse3200/game/ui/terminal/autocomplete/RadixTrie.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DamageMultiplierCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DebugCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DisableDamageCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/DoorOverrideCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/EndScreenCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/InfiniteDashCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/InfiniteJumpsCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/InfiniteStaminaCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/PickupAllCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/TeleportCommand.java
  source/core/src/main/com/csse3200/game/ui/terminal/commands/WinScreenCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/KeyboardTerminalInputComponentTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/TerminalAutocompleteTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/TerminalIntegrationTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/TerminalProcessMessageTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/TouchTerminalInputComponentTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/autocomplete/BKTreeTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/autocomplete/RadixTrieTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/DamageMultiplierCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/DebugCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/DisableDamageCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/DoorOverrideCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/EndScreenCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/FakeCommand.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/PickupAllCommandTests.java
  source/core/src/test/com/csse3200/game/ui/terminal/commands/WavesCommandTests.java
Labels: enhancement, sprint 2, team-5, feature

#211 Weapons Rotation bug
  source/core/src/main/com/csse3200/game/components/player/ItemPickUpComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/items/WorldPickUpFactory.java
  source/core/src/main/com/csse3200/game/entities/spawner/ItemSpawner.java
  source/core/src/test/com/csse3200/game/components/player/ItemPickUpComponentTest.java
Labels: bug, sprint 2, team-1

#235 Difficulty and Platforms
  assets/wiki/ReceptionWiki.png
  assets/wiki/ShippingWiki.png
  assets/wiki/SpawnWiki.png
  assets/wiki/StorageWiki.png
  source/core/assets/backgrounds/Reception.png
  source/core/assets/backgrounds/Shipping.png
  source/core/assets/backgrounds/SpawnResize.png
  source/core/assets/backgrounds/Storage.png
  source/core/assets/foreg_sprites/futuristic/SecurityCamera2.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.41.55.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.26.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.28 3.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.28.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.30 2.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.30.jpeg
  source/core/assets/foreg_sprites/futuristic/WhatsApp Image 2025-08-28 at 14.49.31.jpeg
  source/core/assets/foreg_sprites/futuristic/generated-image (3).png
  source/core/assets/foreg_sprites/office/officeDesk3 Background Removed 3.58.07 am.png
  source/core/assets/foreg_sprites/office/officeDesk3 Background Removed.png
  source/core/assets/foreg_sprites/office/officeDesk4 Background Removed 4.01.48 am.png
  source/core/assets/foreg_sprites/office/officeDesk4 Background Removed.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/Reception.java
  source/core/src/main/com/csse3200/game/areas/ResearchGameArea.java
  source/core/src/main/com/csse3200/game/areas/SecurityGameArea.java
  source/core/src/main/com/csse3200/game/areas/ServerGameArea.java
  source/core/src/main/com/csse3200/game/areas/ShippingGameArea.java
  source/core/src/main/com/csse3200/game/areas/StorageGameArea.java
  source/core/src/main/com/csse3200/game/areas/TunnelGameArea.java
  source/core/src/main/com/csse3200/game/areas/difficulty/Difficulty.java
  source/core/src/main/com/csse3200/game/areas/difficulty/DifficultyType.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/BreakablePlatformComponent.java
  source/core/src/main/com/csse3200/game/components/difficultymenu/DifficultyMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/StaminaComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/KeycardFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/characters/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/system/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/DifficultyScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/DifficultyTest.java
  source/core/src/test/com/csse3200/game/components/BreakablePlatformComponentTest.java
Labels: sprint 3, team-3, feature

#256 Main menu music
  source/core/assets/sounds/menuMusic.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/files/UserSettings.java
  source/core/src/main/com/csse3200/game/services/MusicService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
Labels: sprint 3, team-5, task

#252 Upgrade stations
  source/core/assets/images/blackBG.png
  source/core/assets/images/clearBoots.png
  source/core/assets/images/textbg.png
  source/core/assets/sounds/upgradeSound.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/MagazineComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/stations/StationComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/BenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/ComputerBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/HealthBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/benches/SpeedBenchConfig.java
  source/core/src/test/com/csse3200/game/components/stations/StationComponentTests.java
Labels: sprint 3, team-7, task

#261 Menu button sounds
  source/core/assets/sounds/buttonClick.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/difficultymenu/DifficultyMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/screens/TutorialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/services/ButtonSoundService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
Labels: enhancement, sprint 3, team-5, task

#268 Attachments
  source/core/assets/images/laser.png
  source/core/src/main/com/csse3200/game/components/attachments/LaserComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/screens/ShopScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/shop/PurchaseError.java
  source/core/src/main/com/csse3200/game/components/shop/ShopDemo.java
  source/core/src/main/com/csse3200/game/components/shop/ShopManager.java
  source/core/src/main/com/csse3200/game/entities/factories/items/WeaponsFactory.java
  source/core/src/test/com/csse3200/game/components/player/PlayerActionsTest.java
  source/core/src/test/com/csse3200/game/components/shop/ShopManagerTest.java
Labels: enhancement, sprint 3, team-7, task
