Repository UQcsse3200/2025-studio-1, pull requests merged in 2025-08, with the labels that each got.

#52 Player Animation
  .DS_Store
  source/core/assets/images/player.atlas
  source/core/assets/images/player.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
Labels: sprint 1, team-4, feature

#53 Feature/health system/base
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: sprint 1, to-be-approved, team-5

#59 eHealth system
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: sprint 1, to-be-approved, team-5, feature
